apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: test
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: successful-workers
    template:
      spec:
        completions: 2
        parallelism: 2
        backoffLimit: 0
        template:
          spec:
            restartPolicy: Never
            terminationGracePeriodSeconds: 0
            containers:
            - name: worker
              image: busybox
              command: ['/bin/sh', '-c']
              args:
              - |
                echo "Start"

                while true; do
                  if [ -f /tmp/fail ]; then
                    echo "Exiting 1"
                    exit 1;
                  fi;
                  if [ -f /tmp/succeed ]; then
                    echo "Exiting 0"
                    exit 0;
                  fi;
                  sleep 1;
                done

                echo "End"
  - name: faulty-workers
    template:
      spec:
        completions: 2
        parallelism: 2
        backoffLimit: 0
        template:
          spec:
            restartPolicy: Never
            terminationGracePeriodSeconds: 0
            containers:
            - name: worker
              image: busybox
              command: ['/bin/sh', '-c']
              args:
              - |
                echo "Start"

                while true; do
                  if [ -f /tmp/fail ]; then
                    echo "Exiting 1"
                    exit 1;
                  fi;
                  if [ -f /tmp/succeed ]; then
                    echo "Exiting 0"
                    exit 0;
                  fi;
                  sleep 1;
                done

                echo "End"